--- Create the table 
CREATE TABLE employees (
    id INT4 PRIMARY KEY GENERATED BY DEFAULT AS SEQUENCE employees_id_seq,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    email VARCHAR(100),
    hire_date DATE
);

CREATE UNIQUE INDEX employees_id_uindex ON employees (id);
-- SQL script to insert 100 random employees into the 'employees' table
DO $$
BEGIN
    FOR i IN 1..100 LOOP
        INSERT INTO employees (first_name, last_name, email, hire_date)
        VALUES (
            chr(trunc(65 + random() * 25)::int) || chr(trunc(65 + random() * 25)::int) || chr(trunc(65 + random() * 25)::int),
            chr(trunc(65 + random() * 25)::int) || chr(trunc(65 + random() * 25)::int) || chr(trunc(65 + random() * 25)::int),
            'user' || i || '@example.com',
            CURRENT_DATE - (trunc(random() * 3650)::int)
        );
    END LOOP;
END $$;